### ISSUE TITLE
Issue with css and images on surge

### ISSUE THREAD

**Issue by harsh-wal** [Shruti-1005/myRepo#2]
There looks to be some issue with css and images. Can you change the code and push again to github and surge.

<img width="1440" alt="Screen Shot 2019-09-30 at 11 33 55 AM" src="https://user-images.githubusercontent.com/48089998/65853418-10900c80-e377-11e9-9935-d418f6a93bd7.png">

**Comment by Shruti-1005** [comment]
Hi

Sorry for late reply, have you got that code run?

**Comment by harsh-wal** [comment]
Hi Shruti,

We were able to run it on our local. 

Thanks,
Harsh

**Comment by Shruti-1005** [comment]
Is it fine? actually i was trying to contact sanjana but not able to reach
her. Waiting for her reply.
